version: '3.8'

services:
  backend:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    image: webot-backend:dev
    env_file:
      - ./.env.dev
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    volumes:
      - ./backend/app:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: webot-frontend:dev
    env_file:
      - ./.env.dev
    ports:
      - "3000:5173"
    depends_on:
       - backend
    volumes:
      - ./frontend:/usr/src/app    # monta seu código no container para hot-reload
      - /usr/src/app/node_modules  # preserva node_modules do container

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data:
