version: '3.8'

# Declaração de redes
networks:
  webot-network:
    driver: bridge

# Declaração de volumes
volumes:
  postgres_data:
  redis_data:

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: webot-backend:dev
    env_file:
      - ./.env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER:-webot}:${POSTGRES_PASSWORD:-secret}@postgres:5432/${POSTGRES_DB:-webot_db}"
      REDIS_URL: "redis://:${REDIS_PASSWORD}@redis:6379/0"
      SECRET_KEY: "${SECRET_KEY}"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      ADMIN_EMAIL: "${ADMIN_EMAIL:-admin@example.com}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - webot-network
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - /app/.pytest_cache

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: webot-frontend:dev
    env_file:
      - ./.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - webot-network
    volumes:
        - ./frontend:/usr/src/app
        - /usr/src/app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  postgres:
    image: postgres:14
    container_name: webot-postgres
    env_file:
      - ./.env            
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-webot}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-secret}"
      POSTGRES_DB: "${POSTGRES_DB:-webot_db}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data   
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-webot}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - webot-network    

  redis:
    image: redis:7-alpine
    restart: always
    env_file:
      - ./.env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - webot-network
