[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
skip_gitignore = true

[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$' 