name: CI/CD

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Black & isort
        run: |
          cd backend
          pip install --upgrade pip
          pip install black isort

      - name: Run isort (check-only)
        run: |
          cd backend
          isort --profile black --check-only .

      - name: Run Black (check-only)
        run: |
          cd backend
          black --check .

  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      - name: Run ESLint
        run: |
          cd frontend
          npm run lint

  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    needs: lint-backend
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install backend deps
        run: |
          cd backend
          pip install -r requirements.txt
          pip install -e .
      - name: Run pytest
        run: |
          cd backend
          PYTHONPATH=$PYTHONPATH:$(pwd) pytest --maxfail=1 --disable-warnings -q

  smoke-test-frontend:
    name: Smoke Test Frontend
    runs-on: ubuntu-latest
    needs: lint-frontend
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Build and Test
        run: |
          cd frontend
          npm ci
          npm run build
          npm install --no-save serve
          npx serve -s dist -l 5000 &
          sleep 5
          curl -fs http://localhost:5000 || (echo "Smoke test falhou" && exit 1)

  build-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs:
      - test-backend
      - smoke-test-frontend
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: webot-chatflow-backend:pr-${{ github.event.number }}
      - name: Build Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: webot-chatflow-frontend:pr-${{ github.event.number }}
