name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    name: Run tests (frontend & backend)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Frontend (React + Vite)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install & build frontend
        run: |
          cd frontend
          npm install
          npm run build

      # Backend (Python)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install & test backend
        run: |
          cd backend
          pip install -r requirements.txt
          pytest --maxfail=1 --disable-warnings -q
